class DetailedCompanyParser {
  int account_type;
  String id,
      about,
      address1,
      address2,
      address3,
      city,
      state,
      pin,
      country,
      land_line,
      mobile1,
      mobile2,
      email,
      website,
      longitude,
      latitude,
      contact_first_name,
      contact_last_name,
      sso_id,
      image_bigthumb_url,
      image_smallthumb_url,
      image_url,
      organisation_name,
      brandname_marathi,
      brandname_hindi,
      about_marathi,
      about_hindi,
      dealer_website,
      cover_media_id,
      media_type, image_max_color, image_min_color;

  bool whatsapp_opt_in_status, liked;

  DetailedCompanyParser(
    this.id,
    this.about,
    this.account_type,
    this.address1,
    this.address2,
    this.address3,
    this.city,
    this.state,
    this.pin,
    this.country,
    this.land_line,
    this.mobile1,
    this.mobile2,
    this.email,
    this.website,
    this.longitude,
    this.latitude,
    this.contact_first_name,
    this.contact_last_name,
    this.sso_id,
    this.image_bigthumb_url,
    this.image_smallthumb_url,
    this.image_url,
    this.organisation_name,
    this.brandname_marathi,
    this.brandname_hindi,
    this.about_marathi,
    this.about_hindi,
    this.dealer_website,
    this.cover_media_id,
    this.whatsapp_opt_in_status,
    this.liked,
    this.media_type,
      this.image_max_color,
      this.image_min_color
  );
}
