class WebinarDetails {
  int id, user_id, duration, audience_size, featured;

  String type,
      title,
      about,
      scheduled_date,
      scheduled_time,
      language,
      created_date,
      updated_date,
      image_path,
      status,
      meeting_link,
      meeting_id,
      meeting_password,
      share_link,
      image_path_medium,
      image_path_small,
      price,
      allowed_audience,
      image_bigthumb_url,
      organisation_name,
      first_name,
      last_name,
      mobile,
      media_type,
      media_url,
      in_event,
      addons_name;

  bool nature, is_paid;

  WebinarDetails(
      this.id,
      this.user_id,
      this.type,
      this.title,
      this.about,
      this.scheduled_date,
      this.scheduled_time,
      this.duration,
      this.language,
      this.created_date,
      this.updated_date,
      this.image_path,
      this.status,
      this.meeting_link,
      this.meeting_id,
      this.meeting_password,
      this.share_link,
      this.audience_size,
      this.featured,
      this.image_path_medium,
      this.image_path_small,
      this.price,
      this.media_type,
      this.media_url,
      this.allowed_audience,
      this.image_bigthumb_url,
      this.organisation_name,
      this.first_name,
      this.last_name,
      this.mobile,
      this.in_event,
      this.addons_name);
}
