class WebinarListParser {
  int id, user_id, duration, audience_size, featured, in_event;

  String type,
      title,
      about,
      scheduled_date,
      scheduled_time,
      language,
      created_date,
      updated_date,
      image_path,
      status,
      meeting_link,
      meeting_id,
      meeting_password,
      share_link,
      image_path_medium,
      image_path_small,
      price,
      allowed_audience,
      image_bigthumb_url,
      organisation_name,
      first_name,
      last_name,
      mobile,
      media_type,
      media_url;

  bool nature, is_paid;

  WebinarListParser(
      {this.id,
      this.user_id,
      this.type,
      this.title,
      this.about,
      this.scheduled_date,
      this.scheduled_time,
      this.duration,
      this.language,
      this.created_date,
      this.updated_date,
      this.image_path,
      this.status,
      this.meeting_link,
      this.meeting_id,
      this.meeting_password,
      this.share_link,
      this.audience_size,
      this.featured,
      this.image_path_medium,
      this.image_path_small,
      this.price,
      this.media_type,
      this.media_url,
      this.allowed_audience,
      this.image_bigthumb_url,
      this.organisation_name,
      this.first_name,
      this.last_name,
      this.mobile, this.in_event});

  factory WebinarListParser.fromJson(Map<String, dynamic> json) =>
      WebinarListParser(
          id: json["id"],
          user_id: json["user_id"],
          type: json["type"],
          title: json["title"],
          about: json["about"],
          scheduled_date: json["scheduled_date"],
          scheduled_time: json["scheduled_time"],
          duration: json["duration"],
          language: json["language"],
          created_date: json["created_date"],
          updated_date: json["updated_date"],
          image_path: json["image_path"],
          status: json["status"],
          meeting_link: json["meeting_link"],
          meeting_id: json["meeting_id"],
          meeting_password: json["meeting_password"],
          share_link: json["share_link"],
          audience_size: json["audience_size"],
          featured: json["featured"],
          image_path_medium: json["image_path_medium"],
          image_path_small: json["image_path_small"],
          price: json["price"],
          media_type: json["media_type"],
          media_url: json["media_url"],
          allowed_audience: json["allowed_audience"],
          image_bigthumb_url: json["image_bigthumb_url"],
          organisation_name: json["organisation_name"],
          first_name: json["first_name"],
          last_name: json["last_name"],
          mobile: json["mobile"],
          in_event: json["in_event"]
      );
}
